jobs:
- job: TagImageForIAT
  pool:
    vmImage: 'ubuntu-latest'
  
  steps:
  - task: Docker@2
    displayName: 'Pull WebAPI image'
    inputs:
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      command: pull
      arguments: $(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(CONTAINER_NAME):$(CONTAINER_TAG)

  - task: Docker@2
    displayName: 'Pull Background Service image'
    inputs:
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      command: pull
      arguments: $(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(WIN_CONTAINER_NAME):$(CONTAINER_TAG)

  - task: Docker@2
    displayName: 'Pull High Priority Background Service image'
    inputs:
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      command: pull
      arguments: $(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(HIGHPRIORITY_WIN_CONTAINER_NAME):$(CONTAINER_TAG)

  - task: Docker@2
    displayName: 'Pull Scheduler Service image'
    inputs:
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      command: pull
      arguments: $(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(JOB_CONTAINER_NAME):$(CONTAINER_TAG)

  - task: Docker@2
    displayName: 'Pull Host Kafka Service image'
    inputs:
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      command: pull
      arguments: $(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(KAFKA_CONTAINER_NAME):$(CONTAINER_TAG)

  - task: Docker@2
    displayName: 'Promote WebAPI to IAT'
    inputs:
      command: tag
      arguments: '$(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(CONTAINER_NAME):$(CONTAINER_TAG) $(CONTAINER_REGISTRY_PROJECT_URL)/$(repoEnv)-$(CONTAINER_NAME):$(CONTAINER_TAG)'

  - task: Docker@2
    displayName: 'Promote Background Service to IAT'
    inputs:
      command: tag
      arguments: '$(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(WIN_CONTAINER_NAME):$(CONTAINER_TAG) $(CONTAINER_REGISTRY_PROJECT_URL)/$(repoEnv)-$(WIN_CONTAINER_NAME):$(CONTAINER_TAG)'

  - task: Docker@2
    displayName: 'Promote High Priority Background Service to IAT'
    inputs:
      command: tag
      arguments: '$(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(HIGHPRIORITY_WIN_CONTAINER_NAME):$(CONTAINER_TAG) $(CONTAINER_REGISTRY_PROJECT_URL)/$(repoEnv)-$(HIGHPRIORITY_WIN_CONTAINER_NAME):$(CONTAINER_TAG)'


  - task: Docker@2
    displayName: 'Promote Scheduler Service to IAT'
    inputs:
      command: tag
      arguments: '$(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(JOB_CONTAINER_NAME):$(CONTAINER_TAG) $(CONTAINER_REGISTRY_PROJECT_URL)/$(repoEnv)-$(JOB_CONTAINER_NAME):$(CONTAINER_TAG)'

  - task: Docker@2
    displayName: 'Promote Host Kafka Service to IAT'
    inputs:
      command: tag
      arguments: '$(CONTAINER_REGISTRY_PROJECT_URL)/stg-$(KAFKA_CONTAINER_NAME):$(CONTAINER_TAG) $(CONTAINER_REGISTRY_PROJECT_URL)/$(repoEnv)-$(KAFKA_CONTAINER_NAME):$(CONTAINER_TAG)'

  - task: Docker@2
    displayName: Push Web Service Docker Image
    inputs:
      command: push
      repository: $(repoEnv)-$(CONTAINER_NAME)
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      tags: |
        $(CONTAINER_TAG)

  - task: Docker@2
    displayName: Push Background Service Docker Image
    inputs:
      command: push
      repository: $(repoEnv)-$(WIN_CONTAINER_NAME)
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      tags: |
        $(CONTAINER_TAG)

  - task: Docker@2
    displayName: Push High Priority Background Service Docker Image
    inputs:
      command: push
      repository: $(repoEnv)-$(HIGHPRIORITY_WIN_CONTAINER_NAME)
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      tags: |
        $(CONTAINER_TAG)

  - task: Docker@2
    displayName: Push Scheduler Service Docker Image
    inputs:
      command: push
      repository: $(repoEnv)-$(JOB_CONTAINER_NAME)
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      tags: |
        $(CONTAINER_TAG)
    
  - task: Docker@2
    displayName: Push Host Kafka Service Docker Image
    inputs:
      command: push
      repository: $(repoEnv)-$(KAFKA_CONTAINER_NAME)
      containerRegistry: $(CONTAINER_REGISTRY_PROJECT_SC)
      tags: |
        $(CONTAINER_TAG)