apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    # for payload size increase
    nginx.org/proxy-read-timeout: 100s
    nginx.org/proxy-connect-timeout: 100s
    nginx.org/client-max-body-size: 550m
    nginx.ingress.kubernetes.io/proxy-body-size: 550m
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: dev-business-crispycoffee
  namespace: dev
spec:
  rules:
  - host: crispycoffee.com
    http:
      paths:
      - backend:
          service:
            name: dev-business-crispycoffee
            port:
              number: 80
        path: /api/business-crispycoffee(/|$)(.*)
        pathType: ImplementationSpecific
