apiVersion: v1
kind: Secret
metadata:
  name: datadog-secret
  namespace: datadog
type: Opaque
stringData:
  api-key: 2c7e0ce7fbc908a7fee791bcd875e1ec 
  app-key: 6d3c9f4dc093593573e0fc262876a0556b29ae70