apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opentelemetry-collector
  namespace: argocd
spec:
  project: my-project
  sources:
    # Chart from the Chart Repo
    # Add this repo url in the project repos in Argo
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      targetRevision: 0.108.0
      chart: opentelemetry-collector
      helm:
        valueFiles:
        - $values/ci-cd/argocd/multiple-sources/opentelemetry/k8s-values-deploy.yaml
        ignoreMissingValueFiles: true
    # Values from Git
    - repoURL: https://github.com/upliftlake/devops-dock
      targetRevision: HEAD
      ref: values
    # Other manifests for Opentelemetry
    - repoURL: https://github.com/upliftlake/devops-dock
      targetRevision: HEAD
      path: ci-cd/argocd/multiple-sources/opentelemetry/manifests
      # will not work w/o dir-recurse-true
      directory:
        recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: opentelemetry
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true