# This is a SecretProviderClass example using system-assigned identity to access your key vault
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-system-msi
  namespace: ratan
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"    # Set to true for using managed identity
    userAssignedIdentityID: f8f3bd39-134e-48e6-a98f-fd900e69e7a1      # This is the App-ID of the AppRegistration from Entra having the same name as the Managed Identity; If empty, then defaults to use the system assigned identity on the VM
    keyvaultName: kv-dev
    cloudName: "AzurePublicCloud"                   # [OPTIONAL for Azure] if not provided, the Azure environment defaults to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: mySecret      # the secretName from the kv
          objectType: secret        # object types: secret, key, or cert
          objectVersion: ""         # [OPTIONAL] object versions, default to latest if empty
    tenantId: 1e66ae95-11ad-4a9a-8f12-90b0166b1c7b      # directory-id of the key-vault 
