apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blocks-identity
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-deployed.teams: ArgoDevStgStatus
    notifications.argoproj.io/subscribe.on-health-degraded.teams: ArgoDevStgStatus
  #  notifications.argoproj.io/subscribe.on-sync-succeeded.teams: ArgoDevStgStatus #Teams Channel
  #  notifications.argoproj.io/subscribe.on-sync-failed.teams: ArgoDevStgStatus #Teams Channel
spec:
  project: project-processes-dev
  source:
    repoURL: https://project@dev.azure.com/project/project-Essential/_git/projectProcess-Kubernetes-dev
    targetRevision: HEAD
    path: blocks-identity
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true